name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version:
          - 24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run format:check

      - name: Run tests
        run: npm test
